server:
  port: 8083
  
spring:
  data:
    mongodb:
      uri:  mongodb+srv://venky:venky@cluster0.pcodt.mongodb.net/customers?retryWrites=true&w=majority
      
  application:
    name: CUSTOMER-SERVICE
