server:
  port: 8088
   
spring:  application:    name: Api-Gateway 
 
 
 
zuul:
    routes:
     ADMIN-SERVICE:
      url: http://localhost:8000
     ORDER-SERVICE:
      url: http://localhost:8082
     CUSTOMER-SERVICE:
      url: http://localhost:8083
     WASHER-SERVICE:
      url: http://localhost:8003
     PAYMENT-SERVICE:
      url: http://localhost:8004
       
    