
server:
  port: 8003
  
spring:
  data:
    mongodb:
      uri:  mongodb+srv://venky:venky@cluster0.pcodt.mongodb.net/Washer?retryWrites=true&w=majority
      
  application:
    name: WASHER-SERVICE